name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ] # Handle tag pushes
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # Needed for github-tag-action to push new tags and for docker meta to read code
  packages: write # Required to push to and delete from GHCR

jobs:
  determine_version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only run on push to main
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      version: ${{ steps.tag_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for accurate versioning

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "patch" # Or "minor", "major"

  build_and_push:
    needs: determine_version
    if: always() && (needs.determine_version.result == 'success' || startsWith(github.ref, 'refs/tags/v'))
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            build_type: "release"
            tag_suffix: "amd64"
          - platform: linux/amd64
            runner: ubuntu-latest
            build_type: "debug"
            tag_suffix: "debug-amd64"
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            build_type: "release"
            tag_suffix: "arm64"
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            build_type: "debug"
            tag_suffix: "debug-arm64"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # Release build tags for main branch push
            type=sha,prefix=,suffix=-${{ matrix.tag_suffix }},enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=raw,value=latest-${{ matrix.tag_suffix }},enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=raw,value=${{ needs.determine_version.outputs.new_tag }}-${{ matrix.tag_suffix }},enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.determine_version.outputs.new_tag != '' }}

            # Release build tags for tag push
            type=ref,event=tag,suffix=-${{ matrix.tag_suffix }},enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            BUILD_MODE=${{ matrix.build_type }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create_manifest:
    needs: [determine_version, build_and_push]
    runs-on: ubuntu-latest
    if: always() && (needs.determine_version.result == 'success' || startsWith(github.ref, 'refs/tags/v'))
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest for main branch push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Create manifest for latest
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:latest-amd64 \
            ghcr.io/${{ github.repository }}:latest-arm64

          # Create manifest for latest-debug
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:latest-debug \
            ghcr.io/${{ github.repository }}:latest-debug-amd64 \
            ghcr.io/${{ github.repository }}:latest-debug-arm64

          # Create manifest for version tag
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:${{ needs.determine_version.outputs.new_tag }} \
            ghcr.io/${{ github.repository }}:${{ needs.determine_version.outputs.new_tag }}-amd64 \
            ghcr.io/${{ github.repository }}:${{ needs.determine_version.outputs.new_tag }}-arm64

          # Create manifest for version tag (debug)
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:${{ needs.determine_version.outputs.new_tag }}-debug \
            ghcr.io/${{ github.repository }}:${{ needs.determine_version.outputs.new_tag }}-debug-amd64 \
            ghcr.io/${{ github.repository }}:${{ needs.determine_version.outputs.new_tag }}-debug-arm64

      - name: Create and push manifest for tag push
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Create manifest for version tag
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-amd64 \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-arm64

          # Create manifest for version tag (debug)
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }}-debug \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-debug-amd64 \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-debug-arm64

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Delete architecture-specific tags for main branch push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get package name (lowercase repository name)
          PACKAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | cut -d'/' -f2)
          
          # Get package versions with architecture-specific tags
          VERSIONS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/${PACKAGE_NAME}/versions \
            --jq '.[] | select(.metadata.container.tags[] | test("latest-amd64|latest-arm64|latest-debug-amd64|latest-debug-arm64|${{ needs.determine_version.outputs.new_tag }}-amd64|${{ needs.determine_version.outputs.new_tag }}-arm64|${{ needs.determine_version.outputs.new_tag }}-debug-amd64|${{ needs.determine_version.outputs.new_tag }}-debug-arm64")) | .id')

          # Delete each version
          for VERSION_ID in $VERSIONS; do
            echo "Deleting package version ${VERSION_ID}"
            gh api \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /orgs/${{ github.repository_owner }}/packages/container/${PACKAGE_NAME}/versions/${VERSION_ID} || echo "Failed to delete version ${VERSION_ID}, continuing..."
          done

      - name: Delete architecture-specific tags for tag push
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get package name (lowercase repository name)
          PACKAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | cut -d'/' -f2)
          
          # Get package versions with architecture-specific tags
          VERSIONS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/${PACKAGE_NAME}/versions \
            --jq '.[] | select(.metadata.container.tags[] | test("${{ github.ref_name }}-amd64|${{ github.ref_name }}-arm64|${{ github.ref_name }}-debug-amd64|${{ github.ref_name }}-debug-arm64")) | .id')

          # Delete each version
          for VERSION_ID in $VERSIONS; do
            echo "Deleting package version ${VERSION_ID}"
            gh api \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /orgs/${{ github.repository_owner }}/packages/container/${PACKAGE_NAME}/versions/${VERSION_ID} || echo "Failed to delete version ${VERSION_ID}, continuing..."
          done